In [1]:
## This project is based on Computerphile's Sudoku Solver (https://www.youtube.com/watch?v=G_UYXzGuqvM)
## it uses a backtracking method to brute force a solution to a solveable sudoku.
## To start this example simply run these cells in this order. 
## If you want to solve a custom sudoku, simply insert it manually using the upload_grid() function below.
## Be sure to use te same notation method as below, but that should be quite natural.
## Enjoy!

import numpy as np
from timeit import default_timer as timer

ROW_COUNT = 9
COLUMN_COUNT = 9

def create_grid():
    grid = np.zeros((ROW_COUNT,COLUMN_COUNT), dtype=int)
    return grid

grid = create_grid() 

def disp():
    print(np.matrix(grid))
    
def upload_grid(newgrid):
    global grid
    grid = newgrid
    
def possible(x, y, n):
    global grid
    for i in range (0, 9):
        if grid[i][y] == n:
            return False
    for i in range (0, 9):
        if grid[x][i] == n:
            return False

    x0 = (x // 3) * 3
    y0 = (y // 3) * 3
    for i in range(0, 3):
        for j in range(0, 3):
            if grid[x0 + i][y0 + j] == n:
                return False
    return True

def solve(start=timer()):
    global grid
    for i in range (0, 9):
        for j in range (0, 9):
            if grid[i][j] == 0:
                for n in range(1,10):
                    if possible(i, j, n):
                        grid[i][j] = n
                        solve()
                        grid[i][j] = 0
                return
    disp()
    end = timer()
    elapsedTime = end - start
    print("Found solution in {} seconds".format(round(elapsedTime,8)))
    return



In [2]:
upload_grid([[8, 0, 0, 0, 0, 0, 0, 0, 0],
             [0, 0, 3, 6, 0, 0, 0, 0, 0],
             [0, 7, 0, 0, 9, 0, 2, 0, 0],
             [0, 5, 0, 0, 0, 7, 0, 0, 0],
             [0, 0, 0, 0, 4, 5, 7, 0, 0],
             [0, 0, 0, 1, 0, 0, 0, 3, 0],
             [0, 0, 1, 0, 0, 0, 0, 6, 8],
             [0, 0, 8, 5, 0, 0, 0, 1, 0],
             [0, 9, 0, 0, 0, 0, 4, 0, 0]])

In [3]:
solve()

[[8 1 2 7 5 3 6 4 9]
 [9 4 3 6 8 2 1 7 5]
 [6 7 5 4 9 1 2 8 3]
 [1 5 4 2 3 7 8 9 6]
 [3 6 9 8 4 5 7 2 1]
 [2 8 7 1 6 9 5 3 4]
 [5 2 1 9 7 4 3 6 8]
 [4 3 8 5 2 6 9 1 7]
 [7 9 6 3 1 8 4 5 2]]
Found solution in 19.56071816 seconds
