In [45]:
## This project is based on Computerphile's Sudoku Solver (https://www.youtube.com/watch?v=G_UYXzGuqvM)
## it uses a backtracking method to brute force a solution to a solveable sudoku.
## To start this example simply run these cells in this order. 
## If you want to solve a custom sudoku, simply insert it manually using the upload_grid() function below.
## Be sure to use te same notation method as below, but that should be quite natural.
## Enjoy!

import numpy as np
from timeit import default_timer as timer

ROW_COUNT = 9
COLUMN_COUNT = 9

def create_grid():
    grid = np.zeros((ROW_COUNT,COLUMN_COUNT), dtype=int)
    return grid

grid = create_grid() 

def disp():
    print(np.matrix(grid))
    
def upload_grid(newgrid):
    global grid
    grid = newgrid
    
def possible(x, y, n):
    global grid
    for i in range (0, 9):
        if grid[i][y] == n:
            return False
    for i in range (0, 9):
        if grid[x][i] == n:
            return False

    x0 = (x // 3) * 3
    y0 = (y // 3) * 3
    for i in range(0, 3):
        for j in range(0, 3):
            if grid[x0 + i][y0 + j] == n:
                return False
    return True

def solve():
    start = timer()
    global grid
    for i in range (0, 9):
        for j in range (0, 9):
            if grid[i][j] == 0:
                for n in range(1,10):
                    if possible(i, j, n):
                        grid[i][j] = n
                        solve()
                        grid[i][j] = 0
                return
    disp()
    end = timer()
    elapsedTime = end - start
    print("Found solution in {} seconds".format(elapsedTime))
    



In [46]:
upload_grid([[0, 2, 0, 0, 0, 0, 0, 0, 0],
             [7, 0, 6, 0, 5, 3, 0, 0, 0],
             [0, 4, 0, 9, 6, 0, 3, 0, 8],
             [0, 1, 4, 0, 0, 0, 0, 0, 0],
             [6, 7, 0, 0, 0, 0, 0, 3, 9],
             [0, 0, 0, 0, 0, 0, 1, 4, 0],
             [8, 0, 9, 0, 7, 4, 0, 2, 0],
             [0, 0, 0, 1, 9, 0, 7, 0, 3],
             [0, 0, 0, 0, 0, 0, 0, 5, 0]])

In [47]:
solve()

[[3 2 8 7 4 1 5 9 6]
 [7 9 6 8 5 3 4 1 2]
 [5 4 1 9 6 2 3 7 8]
 [2 1 4 5 3 9 8 6 7]
 [6 7 5 4 1 8 2 3 9]
 [9 8 3 6 2 7 1 4 5]
 [8 5 9 3 7 4 6 2 1]
 [4 6 2 1 9 5 7 8 3]
 [1 3 7 2 8 6 9 5 4]]
Found solution in 0.0004074949993082555 seconds
